# Generated by Django 4.2.17 on 2025-02-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('codigo_climatempo', models.IntegerField(unique=True)),
                ('link_precipitacao', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Clima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidade', models.CharField(max_length=100, unique=True)),
                ('temp_min', models.CharField(blank=True, max_length=10, null=True)),
                ('temp_max', models.CharField(blank=True, max_length=10, null=True)),
                ('sensacao', models.CharField(blank=True, max_length=50, null=True)),
                ('chuva', models.CharField(blank=True, max_length=50, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
